---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: ankit
  become: false
  tasks:

    - name: Start Docker service
      service:
        name: docker
        state: started
  
    - name: Pull Docker Image
      docker_image:
        name: "itsankit123/scientific_calculator_final"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name scientific_calculator_final itsankit123/scientific_calculator_final /bin/bash
